config/routes.rb
Rails.application.routes.draw do
  resources :requests

  root 'welcome#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :course_id, presence: true, length: { minimum: 8 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email #security
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
  end

  def create
    #render plain: params[:request].inspect # just for testing

    # saving data to the controller
    @request = Request.new(request_params)

    @request.save
    redirect_to @request
  end

  def show
    @request = Request.find(params[:id])
  end

  def index
    @requests = Request.all
  end

  private
    def request_params
      params.require(:request).permit(:course_id, :class_id, :start_time, :end_time, :location, :reason, :notes)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cover My Class</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/index.html.erb
<h1>Listing requests</h1>
 
<table>
  <tr>
    <th>Course</th>
    <th>Class</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Location</th>
    <th>Reason</th>
    <th>Notes</th>
  </tr>
 
  <% @requests.each do |request| %>
    <tr>
      <td><%= request.course_id %></td>
      <td><%= request.class_id %></td>
      <td><%= request.start_time %></td>
      <td><%= request.end_time %></td>
      <td><%= request.location %></td>
      <td><%= request.reason %></td>
      <td><%= request.notes %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Home', controller: 'welcome' %> 

app/views/requests/new.html.erb
<h1>Cover my class!</h1>

<%= form_for :request, url: requests_path do |f| %>
  <p>
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </p>
 
  <p>
    <%= f.label :class_id %><br>
    <%= f.text_field :class_id %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :start_time %><br>
    <%= f.datetime_field :start_time %>
  </p>

  <p>
    <%= f.label :end_time %><br>
    <%= f.datetime_field :end_time %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </p>

  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p>
  <strong>Course:</strong>
  <%= @request.course_id %>
</p>
 
<p>
  <strong>Class:</strong>
  <%= @request.class_id %>
</p>
 
<p>
  <strong>Start Time:</strong>
  <%= @request.start_time %>
</p>
 
<p>
  <strong>End Time:</strong>
  <%= @request.end_time %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @request.location %>
</p>
 
<p>
  <strong>Reason:</strong>
  <%= @request.reason %>
</p>
 
<p>
  <strong>Notes:</strong>
  <%= @request.notes %>
</p>

<%= link_to 'Back', requests_path %>

app/views/welcome/index.html.erb
<h1>Cover My Class!</h1>

<%= link_to 'Requests list', controller: 'requests' %> 
<br>
<%= link_to 'Make a request', new_request_path %>